---
language: node_js
node_js:
  - "10"

dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - npm test
  - npm run build -- -prod

# deploy master branch to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $PAGES_DEPLOY_TOKEN
  keep-history: false
  on:
    branch: master
  local-dir: dist
  verbose: true
  fqdn: frosoft.co.uk
